import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import SessionWrapper from "./sessionwrapper";
import { Sidebar } from "@/components/sidebar";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Geets",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex  w-full h-screen overflow-hidden">
					<SessionWrapper>
						<Sidebar className="w-1/6 bg-gray-200" />
						<div className="lg:w-4/5 w-full">{children}</div>
					</SessionWrapper>
					<Toaster />
				</div>
			</body>
		</html>
	);
}
