import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import SessionWrapper from "./sessionwrapper";
import { Sidebar } from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Geets",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex  w-full h-screen ">
					<SessionWrapper>
						<Sidebar className="w-1/5 bg-gray-200" />
						<div className="flex justify-evenly items-center w-4/5 overflow-hidden">
							{children}
						</div>
					</SessionWrapper>
					<Toaster />
				</div>
			</body>
		</html>
	);
}
